# Generated by Django 6.0.3 on 2026-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_authorizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactemployee',
            name='phone',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
