# Generated by Django 6.0.3 on 2026-04-16 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dailyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memo_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('payment_method_details', models.JSONField(blank=True, default=dict)),
                ('authorized_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
