# Generated by Django 6.0.3 on 2026-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_addmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='returned_stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
