# Generated by Django 6.0.3 on 2026-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_returned_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='returned_stock_quantity',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
