# Generated by Django 6.0.3 on 2026-04-21 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='selected_head',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 4, 21)),
            preserve_default=False,
        ),
    ]
