# Generated by Django 6.0.3 on 2026-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_invoiceitem_selected_head_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
