# Generated by Django 6.0.3 on 2026-04-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
