# Generated by Django 6.0.3 on 2026-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_addmoney_created_at_alter_addmoney_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='account_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='finished-goods', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
