# Generated by Django 6.0.3 on 2026-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_shop_addmoney_shop_attendance_shop_check_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
