# Generated by Django 6.0.3 on 2026-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
