# Generated by Django 6.0.3 on 2026-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_invoice_notes_invoice_prepared_by_invoice_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='marriage_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_period',
            field=models.CharField(default='Monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='same_as_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
