# Generated by Django 6.0.3 on 2026-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_employee_department_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
    ]
