# Generated by Django 6.0.3 on 2026-05-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
