# Generated by Django 6.0.3 on 2026-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_attendance_note_attendance_ot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='same_as_local',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
