# Generated by Django 6.0.3 on 2026-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_employee_same_as_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, default='Full-time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_period',
            field=models.CharField(blank=True, default='Monthly', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=50, null=True),
        ),
    ]
