# Generated by Django 6.0.3 on 2026-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_employeetransaction_payment_method_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransaction',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granular permissions per module. Only applies to manager/member roles. Admin always has full access. Keys: dashboard, inventory, sales, purchase, processing, finance, employees, expenses. Values: list of ["view", "add", "edit", "delete", "pay_salary"]. Example: {"employees": ["view", "add"], "sales": ["view"]}'),
        ),
    ]
