# Generated by Django 6.0.3 on 2026-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_employeetransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
