# Generated by Django 6.0.3 on 2026-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_contact_address_line_2_contact_city_contact_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
