# Generated by Django 6.0.3 on 2026-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_product_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
    ]
