# Generated by Django 6.0.3 on 2026-05-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_order_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='app.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=50),
        ),
    ]
