# Generated by Django 6.0.3 on 2026-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_order_invoice_status_invoice_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
    ]
