# Generated by Django 6.0.3 on 2026-05-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_invoice_order_order_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_status',
        ),
    ]
